/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'
import { useSpring, animated } from '@react-spring/three';
import { Mesh } from 'three';

type GLTFResult = GLTF & {
  nodes: {
    Quad_Sphere: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshPhysicalMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/crystal.glb') as any
  const mesh = useRef<Mesh>(null!);
  const [hovered, setHovered] = useState<boolean>(false);
  const { scale } = useSpring({ scale: hovered ? 1.8 : 1.5 });
  useFrame(({clock}) => {
    if (!mesh.current) return;
    mesh.current.rotation.y = clock.getElapsedTime() / 10;
  })

  const onIn = () => {
    setHovered(true);
  }

  const onOut = () => {
    setHovered(false);
  }

  return (
    <group receiveShadow castShadow {...props} dispose={null}>
      <animated.mesh
        onPointerOver={onIn}
        onPointerOut={onOut}
        scale={scale}
        ref={mesh}
        receiveShadow
        castShadow
        geometry={nodes.Quad_Sphere.geometry}
        material={materials.Material}>
          <meshPhysicalMaterial />
      </animated.mesh>

    </group>
  )
}

useGLTF.preload('/crystal.glb')
